#! /bin/sh

bspc monitor -d 1 2 3 4 5

bspc config border_width         5
bspc config window_gap          50
bspc config top_padding 	50
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	true

stalonetray &
nitrogen --restore &
dropbox &
